// sidebars.js — hand-curated, mirrors governance/TAXONOMY.md exactly.
// See governance/SIDEBAR_GUIDE.md before editing. Every category anchors to
// its domain hub; items are in deliberate reading order, not alphabetical.
// Populate each `items` array during stage-04/06 as pages are registered —
// this file starts structurally complete but content-empty on purpose.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: "category",
      label: "Strategy & Operating Model",
      link: { type: "doc", id: "strategy/index" },
      collapsible: true,
      items: [
        "strategy/quantum-ai-consulting-landscape",
        "strategy/quantum-ai-startup-landscape",
        "strategy/ai-value-creator-deliverables-pack",
        "strategy/ai-cost-implementation-guide-2026",
        "strategy/agentic-ai-use-case-value-lifecycle",
        "strategy/ai-coding-agents-2026",
        "strategy/ai-tokenomics-guide",
        "strategy/ai-value-creators-synthesis",
        "strategy/enterprise-ai-commercial-analysis-2026",
        "strategy/foundation-model-companies-2026",
        "strategy/part-01-evolution",
        "strategy/part-02-operating-models",
        "strategy/part-03-ai-delivery-lifecycle",
        "strategy/part-04-genai-delivery",
        "strategy/part-05-agentic-lifecycle",
        "strategy/part-06-governance",
        "strategy/part-07-platform-operating-model",
        "strategy/part-08-organizational-roles",
        "strategy/part-09-operating-processes",
        "strategy/part-10-service-catalog",
        "strategy/part-11-devsecops",
        "strategy/part-12-responsible-ai",
        "strategy/part-13-security-model",
        "strategy/part-14-observability",
        "strategy/part-15-enterprise-architecture",
        "strategy/part-16-financial-model",
        "strategy/part-17-transformation-roadmap",
        "strategy/part-18-case-studies",
        "strategy/part-19-deliverables",
        "strategy/part-20-greenfield-vs-brownfield",
        "strategy/part-21-agentic-process-blueprint",
        "strategy/ea-strategy-playbook",
        "strategy/enterprise-ai-strategic-brief-2026",
        "strategy/enterprise-ai-transformation-blueprint-cto-guide-2026",
        "strategy/executive-summary-and-ai-vision",
        "strategy/current-state-assessment-and-ai-maturity",
        "strategy/ai-opportunity-portfolio",
        "strategy/enterprise-ai-platform-and-data-architecture",
        "strategy/governance-responsible-ai-and-security",
        "strategy/target-operating-model-and-change",
        "strategy/roadmap-financials-kpis-and-risk",
        "strategy/ai-first-to-ai-native",
        "strategy/vol1-corporate-strategy",
        "strategy/vol10-relationship-maps-glossary",
        "strategy/vol2-business-architecture-operating-model",
        "strategy/vol3-portfolio-governance",
        "strategy/vol4-consulting-frameworks-industry",
        "strategy/vol5-ai-strategy-transformation-glossary",
        "strategy/vol6-organization-structure-operating-model",
        "strategy/vol7-enterprise-building-blocks",
        "strategy/vol8-portfolio-consulting-frameworks",
        "strategy/vol9-industry-deep-dives",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/index" },
      collapsible: true,
      items: [
        // "architecture/01-foundations-agentic-loop",
        // "architecture/02-landing-zones",
        // { type: "category", label: "ADR Library",
        //   link: { type: "doc", id: "architecture/adr/index" },
        //   items: ["architecture/adr/adr-001-...", "architecture/adr/adr-002-..."] },
      ],
    },
    {
      type: "category",
      label: "Agentic Systems",
      link: { type: "doc", id: "agentic-systems/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Protocols & Interoperability",
      link: { type: "doc", id: "protocols/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Data & Knowledge",
      link: { type: "doc", id: "data-knowledge/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Platforms & Infrastructure",
      link: { type: "doc", id: "platforms/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Trust: Security, Governance & RAI",
      link: { type: "doc", id: "trust/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Operations & Economics",
      link: { type: "doc", id: "operations/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Learning Paths",
      link: { type: "doc", id: "learning-paths/index" },
      collapsible: true,
      items: [
        // flat list per governance/SIDEBAR_GUIDE.md — no sub-categories
      ],
    },
    {
      type: "category",
      label: "Career & Skills",
      link: { type: "doc", id: "career/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Asset Library",
      link: { type: "doc", id: "assets/index" },
      collapsible: true,
      items: [
        // sub-categories by engagement phase, not file type:
        // { type: "category", label: "Discovery", items: [] },
        // { type: "category", label: "Design", items: [] },
        // { type: "category", label: "Delivery", items: [] },
        // { type: "category", label: "Operate", items: [] },
      ],
    },
  ],
};

module.exports = sidebars;
