// sidebars.js — hand-curated, mirrors governance/TAXONOMY.md exactly.
// See governance/SIDEBAR_GUIDE.md before editing. Every category anchors to
// its domain hub; items are in deliberate reading order, not alphabetical.
// Populate each `items` array during stage-04/06 as pages are registered —
// this file starts structurally complete but content-empty on purpose.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: "category",
      label: "Strategy & Operating Model",
      link: { type: "doc", id: "strategy/index" },
      collapsible: true,
      items: [
        "strategy/quantum-ai-consulting-landscape",
        "strategy/quantum-ai-startup-landscape",
        "strategy/ai-value-creator-deliverables-pack",
        "strategy/ai-cost-implementation-guide-2026",
        "strategy/agentic-ai-use-case-value-lifecycle",
        "strategy/ai-coding-agents-2026",
        "strategy/ai-tokenomics-guide",
        "strategy/ai-value-creators-synthesis",
        "strategy/enterprise-ai-commercial-analysis-2026",
        "strategy/foundation-model-companies-2026",
        "strategy/part-01-evolution",
        "strategy/part-02-operating-models",
        "strategy/part-03-ai-delivery-lifecycle",
        "strategy/part-04-genai-delivery",
        "strategy/part-05-agentic-lifecycle",
        "strategy/part-06-governance",
        "strategy/part-07-platform-operating-model",
        "strategy/part-08-organizational-roles",
        "strategy/part-09-operating-processes",
        "strategy/part-10-service-catalog",
        "strategy/part-11-devsecops",
        "strategy/part-12-responsible-ai",
        "strategy/part-13-security-model",
        "strategy/part-14-observability",
        "strategy/part-15-enterprise-architecture",
        "strategy/part-16-financial-model",
        "strategy/part-17-transformation-roadmap",
        "strategy/part-18-case-studies",
        "strategy/part-19-deliverables",
        "strategy/part-20-greenfield-vs-brownfield",
        "strategy/part-21-agentic-process-blueprint",
        "strategy/ea-strategy-playbook",
        "strategy/enterprise-ai-strategic-brief-2026",
        "strategy/enterprise-ai-transformation-blueprint-cto-guide-2026",
        "strategy/executive-summary-and-ai-vision",
        "strategy/current-state-assessment-and-ai-maturity",
        "strategy/ai-opportunity-portfolio",
        "strategy/enterprise-ai-platform-and-data-architecture",
        "strategy/governance-responsible-ai-and-security",
        "strategy/target-operating-model-and-change",
        "strategy/roadmap-financials-kpis-and-risk",
        "strategy/ai-first-to-ai-native",
        "strategy/vol1-corporate-strategy",
        "strategy/vol10-relationship-maps-glossary",
        "strategy/vol2-business-architecture-operating-model",
        "strategy/vol3-portfolio-governance",
        "strategy/vol4-consulting-frameworks-industry",
        "strategy/vol5-ai-strategy-transformation-glossary",
        "strategy/vol6-organization-structure-operating-model",
        "strategy/vol7-enterprise-building-blocks",
        "strategy/vol8-portfolio-consulting-frameworks",
        "strategy/vol9-industry-deep-dives",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/index" },
      collapsible: true,
      items: [
        "architecture/wiki-governance",
        {
          type: "category",
          label: "AI-DLC & Transformation Frameworks",
          items: [
            "architecture/aidlc-artifacts-discovery-to-model",
            "architecture/parts/aidlc-artifacts-discovery-to-model-feasibility-risk-data-strategy",
            "architecture/parts/aidlc-artifacts-discovery-to-model-model-design-architecture",
            "architecture/aidlc-artifacts-development-to-retirement",
            "architecture/parts/aidlc-artifacts-development-to-retirement-deployment-mlops-retirement",
            "architecture/parts/aidlc-artifacts-development-to-retirement-ea-artifacts",
            "architecture/aidlc-artifacts-togaf-foundation-to-technology",
            "architecture/parts/aidlc-artifacts-togaf-vision-business-architecture",
            "architecture/parts/aidlc-artifacts-togaf-data-application-architecture",
            "architecture/parts/aidlc-artifacts-togaf-technology-architecture",
            "architecture/aidlc-artifacts-togaf-migration-to-ea",
            "architecture/parts/aidlc-artifacts-togaf-change-management-cross-cutting",
            "architecture/parts/aidlc-artifacts-togaf-artifact-cross-reference",
            "architecture/aidlc-agile-cicd-ai-transformation-2026",
            "architecture/parts/aidlc-agile-cicd-agile-evolution-cicd-transformation",
            "architecture/parts/aidlc-agile-cicd-roles-disciplines-roadmap-principles",
            "architecture/aidlc-enterprise-framework-2025",
            "architecture/agile-in-the-age-of-agentic-ai-2026",
            "architecture/ea-aidlc-deep-research-2026",
          ],
        },
        {
          type: "category",
          label: "Frontier AI Research & Industry Outlook",
          items: [
            "architecture/ai-assistant-architecture-research-report",
            "architecture/parts/ai-assistant-architecture-research-report-implementation-evaluation",
            "architecture/ai-deep-future-outlook-2026-2035",
            "architecture/parts/ai-deep-future-outlook-2026-2035-sector-impacts",
            "architecture/ai-lab-research-report-june2026",
            "architecture/ai-native-architecture-evolution-report",
            "architecture/parts/ai-native-architecture-evolution-report-data-paradigms",
            "architecture/parts/ai-native-architecture-evolution-report-decision-forecast",
            "architecture/the-agentic-loop-enterprise-ai-architect-guide",
            "architecture/parts/the-agentic-loop-enterprise-ai-architect-guide-practice-cases",
            "architecture/enterprise-agentic-ai-outlook-2026-2030",
          ],
        },
        {
          type: "category",
          label: "Agentic AI Landing Zone",
          items: [
            "architecture/agentic-ai-landing-zone-architecture",
            "architecture/parts/agentic-ai-landing-zone-architecture-implementation-governance",
            "architecture/agentic-ai-landing-zone-business-layer",
            "architecture/agentic-ai-landing-zone-context-engineering",
            "architecture/agentic-ai-landing-zone-eu-ai-act",
            "architecture/agentic-ai-landing-zone-evaluation",
            "architecture/agentic-ai-landing-zone-memory-architecture",
            "architecture/agentic-ai-landing-zone-multiagent",
            "architecture/agentic-ai-landing-zone-platform-layer",
            "architecture/agentic-ai-landing-zone-playbooks",
            "architecture/agentic-ai-landing-zone-tier3-complete",
            "architecture/agentic-ai-landing-zone-visual-guide",
          ],
        },
        {
          type: "category",
          label: "Foundations: Models & Agent Patterns",
          items: [
            "architecture/transformer-architectures",
            "architecture/transformer-concepts-deep",
            "architecture/ai-value-stream-mapping",
            "architecture/art-framework-agentic-ai-execution",
            "architecture/agentops-production-guide",
            "architecture/agent-as-tool-composition",
            "architecture/agent-interoperability-orchestration",
          ],
        },
        {
          type: "category",
          label: "Agent Reliability, Memory & Governance",
          items: [
            "architecture/agent-memory-planning-architecture",
            "architecture/agent-reliability-engineering",
            "architecture/agentic-ai-reliability-observability-governance",
            "architecture/ai-harness-architecture-orchestration",
            "architecture/drift-detection-guide",
            "architecture/end-to-end-traceability-guide",
            "architecture/enterprise-agent-reference-architectures",
          ],
        },
        {
          type: "category",
          label: "Enterprise AI Architecture Blueprints",
          items: [
            "architecture/enterprise-ai-architect-foundations",
            "architecture/parts/enterprise-ai-architect-foundations-part2",
            "architecture/enterprise-ai-architecture-patterns",
            "architecture/enterprise-ai-comparative-matrices-2026",
            "architecture/enterprise-ai-governance-compliance",
            "architecture/parts/enterprise-ai-governance-compliance-part2",
            "architecture/enterprise-ai-skills-assessment",
            "architecture/parts/enterprise-ai-skills-assessment-part2",
            "architecture/enterprise-aiops-guide",
            "architecture/parts/enterprise-aiops-guide-part2",
            "architecture/enterprise-multi-model-ai-strategy",
            "architecture/parts/enterprise-multi-model-ai-strategy-part2",
            "architecture/parts/enterprise-multi-model-ai-strategy-part3",
          ],
        },
        {
          type: "category",
          label: "Operational Guardrails & Protocols",
          items: [
            "architecture/governance-propagation-chain",
            "architecture/kill-switch-architecture",
            "architecture/machine-readable-ea",
            "architecture/mcp-a2a-protocol-deep-dive",
            "architecture/multi-agent-topology-patterns",
          ],
        },
        {
          type: "category",
          label: "ARB Governance Handbook",
          items: [
            "architecture/volume1-governance-ecosystem-operating-models",
            "architecture/volume2-economics-decision-science",
            "architecture/volume3-knowledge-management-capability-mapping",
            "architecture/volume4-artifact-catalog-quality-attributes",
            "architecture/volume5-review-questions-scorecards",
            "architecture/volume6-banking-industry-deepdive",
            "architecture/volume7-ai-native-arb-case-studies",
            "architecture/volume9-enterprise-reference-repository",
          ],
        },
        {
          type: "category",
          label: "EA Practice & Career Guides",
          items: [
            "architecture/ea-architect-deep-dive-foundation",
            "architecture/ea-architect-deep-dive-five-arenas",
            "architecture/ea-architect-deep-dive-toolkit-practice",
            "architecture/ea-architect-deep-dive-measurement-growth",
            "architecture/apex-ea-team-structure-raci",
            "architecture/apex-ea-aidlc-methodology",
            "architecture/apex-ea-information-systems-architecture",
            "architecture/apex-ea-delivery-governance-reference",
            "architecture/ea-bestpractices-jargon",
            "architecture/ea-glossary-cheatsheet",
            "architecture/executive-communication-framework-guide",
            "architecture/ea-mastery-guide",
            "architecture/parts/ea-mastery-guide-part2",
            "architecture/enterprise-ai-architect-bible-2026",
            "architecture/parts/enterprise-ai-architect-bible-2026-part2",
            "architecture/ea-business-communication-executive-skills",
            "architecture/ea-okr-kpi-research",
            "architecture/enterprise-data-architect-ai-genai",
            "architecture/enterprise-manager-ai-genai",
            "architecture/principal-enterprise-ai-guide-educative",
            "architecture/modern-data-ai-platform-blueprint-2026",
          ],
        },
        {
          type: "category",
          label: "Specialized System Blueprints & Toolkits",
          items: [
            "architecture/ai-solution-lifecycle-deliverables",
            "architecture/parts/ai-solution-lifecycle-deliverables-part2",
            "architecture/parts/ai-solution-lifecycle-deliverables-part3",
            "architecture/enterprise-technology-selection-framework",
            "architecture/parts/enterprise-technology-selection-framework-part2",
            "architecture/ai-invoice-auditor-architecture",
            "architecture/parts/ai-invoice-auditor-architecture-part2",
            "architecture/ai-transformation-consultant-toolkit-2026",
            "architecture/parts/ai-transformation-consultant-toolkit-2026-part2",
            "architecture/akes-addendum-document-update-and-versioning",
            "architecture/parts/akes-addendum-document-update-and-versioning-part2",
            "architecture/dpdp-act-2023-comprehensive-guide",
            "architecture/parts/dpdp-act-2023-comprehensive-guide-part2",
            "architecture/parts/dpdp-act-2023-comprehensive-guide-part3",
            "architecture/eaka-research-study",
            "architecture/parts/eaka-research-study-part2",
            "architecture/parts/eaka-research-study-part3",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Agentic Systems",
      link: { type: "doc", id: "agentic-systems/index" },
      collapsible: true,
      items: [
        {
          type: "category",
          label: "Orchestration & Workflow Engines",
          items: [
            "agentic-systems/orchestration/01-executive-summary",
            "agentic-systems/orchestration/02-evolution-timeline",
            "agentic-systems/orchestration/03-workflow-vs-agent-architecture",
            "agentic-systems/orchestration/04-temporal-deep-dive",
            "agentic-systems/orchestration/05-camunda-deep-dive",
            "agentic-systems/orchestration/06-durable-vs-cognitive-execution",
            "agentic-systems/orchestration/07-ai-coding-orchestrators",
            "agentic-systems/orchestration/08-agent-frameworks-comparison",
            "agentic-systems/orchestration/09-tool-calling-orchestration",
            "agentic-systems/orchestration/10-mcp-impact",
            "agentic-systems/orchestration/11-a2a-orchestration-patterns",
            "agentic-systems/orchestration/12-human-in-the-loop-architectures",
            "agentic-systems/orchestration/13-memory-vs-workflow-state",
            "agentic-systems/orchestration/14-ai-planning-vs-workflow-engines",
            "agentic-systems/orchestration/15-reliability-playbook",
            "agentic-systems/orchestration/16-observability-framework",
            "agentic-systems/orchestration/17-workflow-orchestration-security-architecture",
            "agentic-systems/orchestration/18-enterprise-governance-model",
            "agentic-systems/orchestration/19-reference-architectures",
            "agentic-systems/orchestration/20-decision-matrix",
            "agentic-systems/orchestration/21-future-predictions",
            "agentic-systems/orchestration/22-anti-patterns-catalog",
            "agentic-systems/orchestration/23-capability-maturity-model",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Protocols & Interoperability",
      link: { type: "doc", id: "protocols/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Data & Knowledge",
      link: { type: "doc", id: "data-knowledge/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Platforms & Infrastructure",
      link: { type: "doc", id: "platforms/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Trust: Security, Governance & RAI",
      link: { type: "doc", id: "trust/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Operations & Economics",
      link: { type: "doc", id: "operations/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Learning Paths",
      link: { type: "doc", id: "learning-paths/index" },
      collapsible: true,
      items: [
        // flat list per governance/SIDEBAR_GUIDE.md — no sub-categories
      ],
    },
    {
      type: "category",
      label: "Career & Skills",
      link: { type: "doc", id: "career/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Asset Library",
      link: { type: "doc", id: "assets/index" },
      collapsible: true,
      items: [
        // sub-categories by engagement phase, not file type:
        // { type: "category", label: "Discovery", items: [] },
        // { type: "category", label: "Design", items: [] },
        // { type: "category", label: "Delivery", items: [] },
        // { type: "category", label: "Operate", items: [] },
      ],
    },
  ],
};

module.exports = sidebars;
