// sidebars.js — hand-curated, mirrors governance/TAXONOMY.md exactly.
// See governance/SIDEBAR_GUIDE.md before editing. Every category anchors to
// its domain hub; items are in deliberate reading order, not alphabetical.
// Populate each `items` array during stage-04/06 as pages are registered —
// this file starts structurally complete but content-empty on purpose.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: "category",
      label: "Strategy & Operating Model",
      link: { type: "doc", id: "strategy/index" },
      collapsible: true,
      items: [
        "strategy/quantum-ai-consulting-landscape",
        "strategy/quantum-ai-startup-landscape",
        "strategy/ai-value-creator-deliverables-pack",
        "strategy/ai-cost-implementation-guide-2026",
        "strategy/agentic-ai-use-case-value-lifecycle",
        "strategy/ai-coding-agents-2026",
        "strategy/ai-tokenomics-guide",
        "strategy/ai-value-creators-synthesis",
        "strategy/enterprise-ai-commercial-analysis-2026",
        "strategy/foundation-model-companies-2026",
        "strategy/part-01-evolution",
        "strategy/part-02-operating-models",
        "strategy/part-03-ai-delivery-lifecycle",
        "strategy/part-04-genai-delivery",
        "strategy/part-05-agentic-lifecycle",
        "strategy/part-06-governance",
        "strategy/part-07-platform-operating-model",
        "strategy/part-08-organizational-roles",
        "strategy/part-09-operating-processes",
        "strategy/part-10-service-catalog",
        "strategy/part-11-devsecops",
        "strategy/part-12-responsible-ai",
        "strategy/part-13-security-model",
        "strategy/part-14-observability",
        "strategy/part-15-enterprise-architecture",
        "strategy/part-16-financial-model",
        "strategy/part-17-transformation-roadmap",
        "strategy/part-18-case-studies",
        "strategy/part-19-deliverables",
        "strategy/part-20-greenfield-vs-brownfield",
        "strategy/part-21-agentic-process-blueprint",
        "strategy/ea-strategy-playbook",
        "strategy/enterprise-ai-strategic-brief-2026",
        "strategy/enterprise-ai-transformation-blueprint-cto-guide-2026",
        "strategy/executive-summary-and-ai-vision",
        "strategy/current-state-assessment-and-ai-maturity",
        "strategy/ai-opportunity-portfolio",
        "strategy/enterprise-ai-platform-and-data-architecture",
        "strategy/governance-responsible-ai-and-security",
        "strategy/target-operating-model-and-change",
        "strategy/roadmap-financials-kpis-and-risk",
        "strategy/ai-first-to-ai-native",
        "strategy/vol1-corporate-strategy",
        "strategy/vol10-relationship-maps-glossary",
        "strategy/vol2-business-architecture-operating-model",
        "strategy/vol3-portfolio-governance",
        "strategy/vol4-consulting-frameworks-industry",
        "strategy/vol5-ai-strategy-transformation-glossary",
        "strategy/vol6-organization-structure-operating-model",
        "strategy/vol7-enterprise-building-blocks",
        "strategy/vol8-portfolio-consulting-frameworks",
        "strategy/vol9-industry-deep-dives",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/index" },
      collapsible: true,
      items: [
        "architecture/00-wiki-governance",
        {
          type: "category",
          label: "AI-DLC & Transformation Frameworks",
          items: [
            "architecture/01-aidlc-artifacts-discovery-to-model",
            "architecture/parts/01-aidlc-artifacts-discovery-to-model-feasibility-risk-data-strategy",
            "architecture/parts/02-aidlc-artifacts-discovery-to-model-model-design-architecture",
            "architecture/02-aidlc-artifacts-development-to-retirement",
            "architecture/parts/03-aidlc-artifacts-development-to-retirement-deployment-mlops-retirement",
            "architecture/parts/04-aidlc-artifacts-development-to-retirement-ea-artifacts",
            "architecture/03-aidlc-artifacts-togaf-foundation-to-technology",
            "architecture/parts/05-aidlc-artifacts-togaf-vision-business-architecture",
            "architecture/parts/06-aidlc-artifacts-togaf-data-application-architecture",
            "architecture/parts/07-aidlc-artifacts-togaf-technology-architecture",
            "architecture/04-aidlc-artifacts-togaf-migration-to-ea",
            "architecture/parts/08-aidlc-artifacts-togaf-change-management-cross-cutting",
            "architecture/parts/09-aidlc-artifacts-togaf-artifact-cross-reference",
            "architecture/13-aidlc-agile-cicd-ai-transformation-2026",
            "architecture/parts/10-aidlc-agile-cicd-agile-evolution-cicd-transformation",
            "architecture/parts/11-aidlc-agile-cicd-roles-disciplines-roadmap-principles",
            "architecture/14-aidlc-enterprise-framework-2025",
            "architecture/15-agile-in-the-age-of-agentic-ai-2026",
            "architecture/16-ea-aidlc-deep-research-2026",
          ],
        },
        {
          type: "category",
          label: "Frontier AI Research & Industry Outlook",
          items: [
            "architecture/17-ai-assistant-architecture-research-report",
            "architecture/parts/16-ai-assistant-architecture-research-report-implementation-evaluation",
            "architecture/18-ai-deep-future-outlook-2026-2035",
            "architecture/parts/15-ai-deep-future-outlook-2026-2035-sector-impacts",
            "architecture/19-ai-lab-research-report-june2026",
            "architecture/20-ai-native-architecture-evolution-report",
            "architecture/parts/12-ai-native-architecture-evolution-report-data-paradigms",
            "architecture/parts/13-ai-native-architecture-evolution-report-decision-forecast",
            "architecture/21-the-agentic-loop-enterprise-ai-architect-guide",
            "architecture/parts/17-the-agentic-loop-enterprise-ai-architect-guide-practice-cases",
            "architecture/33-enterprise-agentic-ai-outlook-2026-2030",
          ],
        },
        {
          type: "category",
          label: "Agentic AI Landing Zone",
          items: [
            "architecture/22-agentic-ai-landing-zone-architecture",
            "architecture/parts/14-agentic-ai-landing-zone-architecture-implementation-governance",
            "architecture/23-agentic-ai-landing-zone-business-layer",
            "architecture/24-agentic-ai-landing-zone-context-engineering",
            "architecture/25-agentic-ai-landing-zone-eu-ai-act",
            "architecture/26-agentic-ai-landing-zone-evaluation",
            "architecture/27-agentic-ai-landing-zone-memory-architecture",
            "architecture/28-agentic-ai-landing-zone-multiagent",
            "architecture/29-agentic-ai-landing-zone-platform-layer",
            "architecture/30-agentic-ai-landing-zone-playbooks",
            "architecture/31-agentic-ai-landing-zone-tier3-complete",
            "architecture/32-agentic-ai-landing-zone-visual-guide",
          ],
        },
        {
          type: "category",
          label: "Foundations: Models & Agent Patterns",
          items: [
            "architecture/34-transformer-architectures",
            "architecture/35-transformer-concepts-deep",
            "architecture/36-ai-value-stream-mapping",
            "architecture/37-art-framework-agentic-ai-execution",
            "architecture/38-agentops-production-guide",
            "architecture/39-agent-as-tool-composition",
            "architecture/40-agent-interoperability-orchestration",
          ],
        },
        {
          type: "category",
          label: "Agent Reliability, Memory & Governance",
          items: [
            "architecture/41-agent-memory-planning-architecture",
            "architecture/42-agent-reliability-engineering",
            "architecture/43-agentic-ai-reliability-observability-governance",
            "architecture/44-ai-harness-architecture-orchestration",
            "architecture/45-drift-detection-guide",
            "architecture/46-end-to-end-traceability-guide",
            "architecture/47-enterprise-agent-reference-architectures",
          ],
        },
        {
          type: "category",
          label: "Enterprise AI Architecture Blueprints",
          items: [
            "architecture/48-enterprise-ai-architect-foundations",
            "architecture/parts/23-enterprise-ai-architect-foundations-part2",
            "architecture/49-enterprise-ai-architecture-patterns",
            "architecture/50-enterprise-ai-comparative-matrices-2026",
            "architecture/51-enterprise-ai-governance-compliance",
            "architecture/parts/22-enterprise-ai-governance-compliance-part2",
            "architecture/52-enterprise-ai-skills-assessment",
            "architecture/parts/21-enterprise-ai-skills-assessment-part2",
            "architecture/53-enterprise-aiops-guide",
            "architecture/parts/20-enterprise-aiops-guide-part2",
            "architecture/54-enterprise-multi-model-ai-strategy",
            "architecture/parts/18-enterprise-multi-model-ai-strategy-part2",
            "architecture/parts/19-enterprise-multi-model-ai-strategy-part3",
          ],
        },
        {
          type: "category",
          label: "Operational Guardrails & Protocols",
          items: [
            "architecture/55-governance-propagation-chain",
            "architecture/56-kill-switch-architecture",
            "architecture/57-machine-readable-ea",
            "architecture/58-mcp-a2a-protocol-deep-dive",
            "architecture/59-multi-agent-topology-patterns",
          ],
        },
        {
          type: "category",
          label: "ARB Governance Handbook",
          items: [
            "architecture/60-volume1-governance-ecosystem-operating-models",
            "architecture/61-volume2-economics-decision-science",
            "architecture/62-volume3-knowledge-management-capability-mapping",
            "architecture/63-volume4-artifact-catalog-quality-attributes",
            "architecture/64-volume5-review-questions-scorecards",
            "architecture/65-volume6-banking-industry-deepdive",
            "architecture/66-volume7-ai-native-arb-case-studies",
            "architecture/67-volume9-enterprise-reference-repository",
          ],
        },
        {
          type: "category",
          label: "EA Practice & Career Guides",
          items: [
            "architecture/05-ea-architect-deep-dive-foundation",
            "architecture/06-ea-architect-deep-dive-five-arenas",
            "architecture/07-ea-architect-deep-dive-toolkit-practice",
            "architecture/08-ea-architect-deep-dive-measurement-growth",
            "architecture/09-apex-ea-team-structure-raci",
            "architecture/10-apex-ea-aidlc-methodology",
            "architecture/11-apex-ea-information-systems-architecture",
            "architecture/12-apex-ea-delivery-governance-reference",
            "architecture/68-ea-bestpractices-jargon",
            "architecture/69-ea-glossary-cheatsheet",
            "architecture/70-executive-communication-framework-guide",
            "architecture/71-ea-mastery-guide",
            "architecture/parts/35-ea-mastery-guide-part2",
            "architecture/72-enterprise-ai-architect-bible-2026",
            "architecture/parts/24-enterprise-ai-architect-bible-2026-part2",
            "architecture/82-ea-business-communication-executive-skills",
            "architecture/83-ea-okr-kpi-research",
            "architecture/84-enterprise-data-architect-ai-genai",
            "architecture/85-enterprise-manager-ai-genai",
            "architecture/86-principal-enterprise-ai-guide-educative",
            "architecture/87-modern-data-ai-platform-blueprint-2026",
          ],
        },
        {
          type: "category",
          label: "Specialized System Blueprints & Toolkits",
          items: [
            "architecture/74-ai-solution-lifecycle-deliverables",
            "architecture/parts/28-ai-solution-lifecycle-deliverables-part2",
            "architecture/parts/29-ai-solution-lifecycle-deliverables-part3",
            "architecture/75-enterprise-technology-selection-framework",
            "architecture/parts/25-enterprise-technology-selection-framework-part2",
            "architecture/76-ai-invoice-auditor-architecture",
            "architecture/parts/26-ai-invoice-auditor-architecture-part2",
            "architecture/77-ai-transformation-consultant-toolkit-2026",
            "architecture/parts/27-ai-transformation-consultant-toolkit-2026-part2",
            "architecture/78-akes-addendum-document-update-and-versioning",
            "architecture/parts/30-akes-addendum-document-update-and-versioning-part2",
            "architecture/79-dpdp-act-2023-comprehensive-guide",
            "architecture/parts/31-dpdp-act-2023-comprehensive-guide-part2",
            "architecture/parts/32-dpdp-act-2023-comprehensive-guide-part3",
            "architecture/81-eaka-research-study",
            "architecture/parts/33-eaka-research-study-part2",
            "architecture/parts/34-eaka-research-study-part3",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Agentic Systems",
      link: { type: "doc", id: "agentic-systems/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Protocols & Interoperability",
      link: { type: "doc", id: "protocols/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Data & Knowledge",
      link: { type: "doc", id: "data-knowledge/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Platforms & Infrastructure",
      link: { type: "doc", id: "platforms/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Trust: Security, Governance & RAI",
      link: { type: "doc", id: "trust/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Operations & Economics",
      link: { type: "doc", id: "operations/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Learning Paths",
      link: { type: "doc", id: "learning-paths/index" },
      collapsible: true,
      items: [
        // flat list per governance/SIDEBAR_GUIDE.md — no sub-categories
      ],
    },
    {
      type: "category",
      label: "Career & Skills",
      link: { type: "doc", id: "career/index" },
      collapsible: true,
      items: [],
    },
    {
      type: "category",
      label: "Asset Library",
      link: { type: "doc", id: "assets/index" },
      collapsible: true,
      items: [
        // sub-categories by engagement phase, not file type:
        // { type: "category", label: "Discovery", items: [] },
        // { type: "category", label: "Design", items: [] },
        // { type: "category", label: "Delivery", items: [] },
        // { type: "category", label: "Operate", items: [] },
      ],
    },
  ],
};

module.exports = sidebars;
